### ISSUE TITLE
Question regarding AdminLTE3.MVC

### ISSUE THREAD

**Issue by KennyLee-Custodio** [somaraj/AdminLTE-VS-Template#1]
Is this supposed to be [AdminLTE3.MVC](https://www.nuget.org/packages/AdminLTE3.MVC/) from NuGet?

How are you planning to support in on MVC?

**Comment by somaraj** [comment]
What I am planing here is a **Visual Studio project template** for creating new project with AdminLTE 3 support. 

This will be avaliable as **Visual Studio 2019 extension**  (VSIX) in [marketplace](https://marketplace.visualstudio.com/publishers/somaraj) once ready

![Annotation 2020-02-15 003434](https://user-images.githubusercontent.com/17797942/74559696-01f36c00-4f8b-11ea-981e-9648a5724aef.jpg)

**Comment by KennyLee-Custodio** [comment]
Not sure how I could help, but would love to be involved as much as I can if you need it.

**Comment by somaraj** [comment]
Much appreciated. I have pushed the initial version, now we can collabrate as a team.
